"""
Command-line entry point for the ingestion layer.
"""

from pathlib import Path

import argparse
import sys
from datetime import date

from ingestion.aemet.ingest import AemetIngestion
from ingestion.cnig.ingest import CnigIngestion
from ingestion.common.exceptions import IngestionError
from ingestion.common.logger import get_logger
from ingestion.esios.ingest import EsiosIngestion
from ingestion.open_meteo.ingest import OpenMeteoIngestion


logger = get_logger(__name__)


def parse_date(value: str) -> date:
    """
    Convert an ISO date string (YYYY-MM-DD) into a date object.
    """

    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"Invalid date '{value}'. Expected format: YYYY-MM-DD."
        ) from exc


def build_parser() -> argparse.ArgumentParser:
    """
    Build the command-line argument parser.
    """

    parser = argparse.ArgumentParser(
        description="Energy Lakehouse Platform ingestion CLI."
    )

    subparsers = parser.add_subparsers(
        dest="source",
        required=True,
    )

    open_meteo_parser = subparsers.add_parser(
        "open_meteo",
        help="Run Open-Meteo ingestion.",
    )

    open_meteo_parser.add_argument(
        "--mode",
        choices=(
            "historical",
            "minutely_15",
        ),
        required=True,
    )

    open_meteo_parser.add_argument(
        "--latitude",
        type=float,
        required=True,
    )

    open_meteo_parser.add_argument(
        "--longitude",
        type=float,
        required=True,
    )

    open_meteo_parser.add_argument(
        "--station-id",
        required=True,
    )

    open_meteo_parser.add_argument(
        "--start-date",
        type=parse_date,
    )

    open_meteo_parser.add_argument(
        "--end-date",
        type=parse_date,
    )

    aemet_parser = subparsers.add_parser(
        "aemet",
        help="Run AEMET ingestion.",
    )

    aemet_parser.add_argument(
        "--mode",
        choices=(
            "stations",
            "observations",
        ),
        required=True,
    )

    subparsers.add_parser(
        "cnig",
        help="Run CNIG / IGN master-data ingestion.",
    )

    esios_parser = subparsers.add_parser(
        "esios",
        help="Run REE / ESIOS ingestion.",
    )

    esios_parser.add_argument(
        "--mode",
        choices=(
            "historical",
            "incremental",
        ),
        required=True,
    )

    esios_parser.add_argument(
        "--indicator-id",
        type=int,
        required=True,
    )

    esios_parser.add_argument(
        "--dataset",
        required=True,
    )

    esios_parser.add_argument(
        "--start-date",
        type=parse_date,
        required=True,
    )

    esios_parser.add_argument(
        "--end-date",
        type=parse_date,
        required=True,
    )

    esios_parser.add_argument(
        "--time-trunc",
    )

    esios_parser.add_argument(
        "--time-agg",
    )

    esios_parser.add_argument(
        "--geo-trunc",
    )

    esios_parser.add_argument(
        "--geo-agg",
    )

    esios_parser.add_argument(
        "--geo-id",
        dest="geo_ids",
        type=int,
        action="append",
    )

    return parser




def validate_date_arguments(
    args: argparse.Namespace,
) -> None:
    """
    Validate source-specific date requirements.
    """

    if args.source == "open_meteo":
        if args.start_date is None or args.end_date is None:
            raise ValueError(
                f"Open-Meteo mode '{args.mode}' requires "
                "--start-date and --end-date."
            )




def log_output_paths(
    output: Path | str | list[Path | str],
) -> None:
    """
    Log the Bronze files generated by an ingestion execution.
    """

    if isinstance(output, list):
        logger.info(
            "%s Bronze files generated.",
            len(output),
        )

        for path in output:
            logger.info(
                "Generated Bronze file: %s",
                path,
            )
    else:
        logger.info(
            "Generated Bronze file: %s",
            output,
        )


def run_open_meteo(
    args: argparse.Namespace,
) -> None:
    """Execute Open-Meteo ingestion."""

    ingestion = OpenMeteoIngestion()

    if args.mode == "historical":
        output = ingestion.ingest_historical(
            latitude=args.latitude,
            longitude=args.longitude,
            start_date=args.start_date,
            end_date=args.end_date,
            station_id=args.station_id,
        )

    else:
        from datetime import datetime, timezone

        start_datetime = datetime.combine(
            args.start_date,
            datetime.min.time(),
            tzinfo=timezone.utc,
        )

        end_datetime = datetime.combine(
            args.end_date,
            datetime.max.time(),
            tzinfo=timezone.utc,
        )

        output = ingestion.ingest_minutely_15(
            latitude=args.latitude,
            longitude=args.longitude,
            start_datetime=start_datetime,
            end_datetime=end_datetime,
            location_id=args.station_id,
        )

    log_output_paths(output)



def run_aemet(
    args: argparse.Namespace,
) -> None:
    """Execute active AEMET ingestion."""

    ingestion = AemetIngestion()

    if args.mode == "stations":
        output = ingestion.ingest_stations()

    elif args.mode == "observations":
        output = (
            ingestion
            .ingest_current_observations()
        )

    else:
        raise ValueError(
            f"Unsupported AEMET mode: {args.mode}"
        )

    log_output_paths(output)




def run_cnig() -> None:
    """Execute CNIG / IGN master-data ingestion."""

    ingestion = CnigIngestion()
    output = ingestion.ingest_ngmep()

    log_output_paths(output)

def run_esios(
    args: argparse.Namespace,
) -> None:
    """Execute REE / ESIOS ingestion."""

    ingestion = EsiosIngestion()

    common_arguments = {
        "indicator_id": args.indicator_id,
        "dataset": args.dataset,
        "start_date": args.start_date,
        "end_date": args.end_date,
        "time_trunc": args.time_trunc,
        "time_agg": args.time_agg,
        "geo_ids": args.geo_ids,
        "geo_trunc": args.geo_trunc,
        "geo_agg": args.geo_agg,
    }

    if args.mode == "historical":
        output = ingestion.ingest_historical(
            **common_arguments
        )
    else:
        output = ingestion.ingest_incremental(
            **common_arguments
        )

    log_output_paths(output)


def main() -> int:
    """
    Execute the ingestion command-line interface.
    """

    parser = build_parser()
    args = parser.parse_args()

    try:
        validate_date_arguments(args)

        if args.source == "open_meteo":
            run_open_meteo(args)

        elif args.source == "aemet":
            run_aemet(args)

        elif args.source == "cnig":
            run_cnig()

        elif args.source == "esios":
            run_esios(args)

        else:
            parser.error(
                f"Unsupported ingestion source: {args.source}"
            )

    except (IngestionError, ValueError) as exc:
        logger.error(
            "Ingestion failed: %s",
            exc,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())